CREATE TABLE IF NOT EXISTS ai_users (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  account VARCHAR(120) NULL,
  phone VARCHAR(32) NULL,
  email VARCHAR(160) NULL,
  password_hash VARCHAR(255) NULL,
  invite_code VARCHAR(64) NULL,
  credits INT NOT NULL DEFAULT 0,
  membership_plan_id BIGINT NULL,
  membership_status VARCHAR(32) NOT NULL DEFAULT 'none',
  membership_expires_at DATETIME NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_ai_users_account (account),
  KEY idx_ai_users_phone (phone),
  KEY idx_ai_users_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_service_providers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  display_name VARCHAR(120) NULL,
  service_type VARCHAR(32) NOT NULL,
  provider VARCHAR(80) NOT NULL,
  default_url VARCHAR(500) NULL,
  icon VARCHAR(500) NULL,
  website VARCHAR(500) NULL,
  rank INT NOT NULL DEFAULT 0,
  is_third_party TINYINT(1) NOT NULL DEFAULT 0,
  support_open_ai TINYINT(1) NOT NULL DEFAULT 0,
  preset_models JSON NULL,
  description TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_ai_service_providers_provider (provider),
  KEY idx_ai_service_providers_service (service_type, is_active, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_service_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  service_type VARCHAR(32) NOT NULL,
  provider VARCHAR(80) NULL,
  name VARCHAR(120) NOT NULL,
  base_url VARCHAR(500) NOT NULL,
  api_key VARCHAR(1000) NOT NULL,
  model JSON NULL,
  endpoint VARCHAR(500) NULL,
  query_endpoint VARCHAR(500) NULL,
  priority INT NOT NULL DEFAULT 0,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  settings JSON NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_ai_service_configs_service (service_type, provider, is_active, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_user_provider_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL,
  provider_id BIGINT NOT NULL,
  provider VARCHAR(80) NOT NULL,
  name VARCHAR(120) NOT NULL,
  base_url VARCHAR(500) NOT NULL,
  api_key VARCHAR(1000) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_ai_user_provider_configs_user_provider (user_id, provider, is_active, is_deleted),
  KEY idx_ai_user_provider_configs_user_provider_id (user_id, provider_id, is_active, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_model_parameter_profiles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  profile_key VARCHAR(120) NOT NULL,
  name VARCHAR(120) NOT NULL,
  service_type VARCHAR(32) NOT NULL,
  description TEXT NULL,
  is_builtin TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_parameter_profiles_key (profile_key),
  KEY idx_parameter_profiles_service (service_type, is_active, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_model_parameter_profile_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  profile_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  label VARCHAR(120) NOT NULL,
  value VARCHAR(255) NOT NULL,
  min_value DOUBLE NULL,
  max_value DOUBLE NULL,
  step_value DOUBLE NULL,
  unit VARCHAR(32) NULL,
  placeholder VARCHAR(255) NULL,
  options_source VARCHAR(120) NULL,
  rank INT NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_profile_items_profile (profile_id, type, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_model_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NULL,
  provider_id BIGINT NULL,
  source_model_id BIGINT NULL,
  parameter_profile_id BIGINT NULL,
  service_type VARCHAR(32) NOT NULL,
  provider VARCHAR(80) NOT NULL,
  model_id VARCHAR(180) NOT NULL,
  name VARCHAR(180) NOT NULL,
  description TEXT NULL,
  base_url VARCHAR(500) NULL,
  endpoint VARCHAR(500) NULL,
  query_endpoint VARCHAR(500) NULL,
  cost DOUBLE NOT NULL DEFAULT 0,
  is_free TINYINT(1) NOT NULL DEFAULT 0,
  member_only TINYINT(1) NOT NULL DEFAULT 0,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  priority INT NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_ai_models_service_default (service_type, is_default, is_active, is_deleted),
  KEY idx_ai_models_model (service_type, model_id, is_active, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_model_billing_rules (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  model_config_id BIGINT NOT NULL,
  service_type VARCHAR(32) NOT NULL,
  parameter_type VARCHAR(32) NOT NULL,
  parameter_value VARCHAR(120) NOT NULL,
  credits INT NOT NULL DEFAULT 0,
  unit VARCHAR(32) NOT NULL DEFAULT 'request',
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_model_billing_rule (model_config_id, parameter_type, parameter_value),
  KEY idx_model_billing_rules_service (service_type, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(120) NOT NULL,
  setting_value TEXT NULL,
  group_name VARCHAR(64) NOT NULL DEFAULT 'system',
  label VARCHAR(120) NULL,
  value_type VARCHAR(32) NOT NULL DEFAULT 'string',
  is_secret TINYINT(1) NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_system_settings_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS credit_packages (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(120) NOT NULL,
  description TEXT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  credits INT NOT NULL DEFAULT 0,
  bonus_credits INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_credit_packages_code (code),
  KEY idx_credit_packages_active (is_active, is_deleted, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS membership_plans (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  code VARCHAR(120) NOT NULL,
  description TEXT NULL,
  plan_type VARCHAR(32) NOT NULL DEFAULT 'creator',
  billing_cycle VARCHAR(32) NOT NULL DEFAULT 'yearly',
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  original_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  credits INT NOT NULL DEFAULT 0,
  duration_days INT NOT NULL DEFAULT 30,
  badge VARCHAR(120) NULL,
  subtitle VARCHAR(255) NULL,
  metadata JSON NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_membership_plans_code (code),
  KEY idx_membership_plans_type (plan_type, billing_cycle, is_active, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS points_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL,
  amount INT NOT NULL,
  balance INT NOT NULL DEFAULT 0,
  type VARCHAR(32) NOT NULL,
  description VARCHAR(500) NULL,
  related_order_id BIGINT NULL,
  related_task_id VARCHAR(120) NULL,
  task_type VARCHAR(64) NULL,
  model VARCHAR(180) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'completed',
  metadata JSON NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_points_logs_user (user_id, created_at),
  KEY idx_points_logs_task (related_task_id, task_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS image_generations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  storyboard_id BIGINT NULL,
  drama_id BIGINT NULL,
  scene_id BIGINT NULL,
  character_id BIGINT NULL,
  prop_id BIGINT NULL,
  image_type VARCHAR(64) NULL,
  frame_type VARCHAR(64) NULL,
  provider VARCHAR(80) NULL,
  prompt TEXT NULL,
  negative_prompt TEXT NULL,
  model VARCHAR(180) NULL,
  size VARCHAR(80) NULL,
  sample_image_size VARCHAR(80) NULL,
  quality VARCHAR(80) NULL,
  style VARCHAR(120) NULL,
  steps INT NULL,
  cfg_scale DOUBLE NULL,
  seed BIGINT NULL,
  output_format VARCHAR(255) NULL,
  response_format VARCHAR(255) NULL,
  watermark TINYINT(1) NULL,
  stream TINYINT(1) NULL,
  official_fallback TINYINT(1) NULL,
  output_compression INT NULL,
  background VARCHAR(255) NULL,
  moderation VARCHAR(255) NULL,
  input_fidelity VARCHAR(255) NULL,
  partial_images INT NULL,
  google_search TINYINT(1) NULL,
  google_image_search TINYINT(1) NULL,
  sequential_image_generation VARCHAR(255) NULL,
  sequential_image_generation_options JSON NULL,
  optimize_prompt_options JSON NULL,
  tools JSON NULL,
  image_url VARCHAR(1000) NULL,
  minio_url VARCHAR(1000) NULL,
  local_path VARCHAR(1000) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  task_id VARCHAR(180) NULL,
  error_msg TEXT NULL,
  width INT NULL,
  height INT NULL,
  reference_images JSON NULL,
  mask LONGTEXT NULL,
  completed_at DATETIME NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_image_generations_user_task (created_by, task_id),
  KEY idx_image_generations_storyboard (storyboard_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS video_generations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  storyboard_id BIGINT NULL,
  drama_id BIGINT NULL,
  provider VARCHAR(80) NULL,
  prompt TEXT NULL,
  model VARCHAR(180) NULL,
  image_gen_id BIGINT NULL,
  reference_mode VARCHAR(64) NULL,
  image_url VARCHAR(1000) NULL,
  first_frame_url VARCHAR(1000) NULL,
  last_frame_url VARCHAR(1000) NULL,
  reference_image_urls JSON NULL,
  duration INT NULL,
  fps INT NULL,
  resolution VARCHAR(80) NULL,
  aspect_ratio VARCHAR(32) NULL,
  style VARCHAR(120) NULL,
  motion_level INT NULL,
  camera_motion VARCHAR(120) NULL,
  seed BIGINT NULL,
  video_url VARCHAR(1000) NULL,
  minio_url VARCHAR(1000) NULL,
  local_path VARCHAR(1000) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  task_id VARCHAR(180) NULL,
  error_msg TEXT NULL,
  width INT NULL,
  height INT NULL,
  completed_at DATETIME NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_video_generations_user_task (created_by, task_id),
  KEY idx_video_generations_storyboard (storyboard_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storyboards (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  episode_id BIGINT NOT NULL,
  scene_id BIGINT NULL,
  storyboard_number INT NOT NULL,
  title VARCHAR(180) NULL,
  dialogue TEXT NULL,
  composed_image VARCHAR(1000) NULL,
  first_frame_image VARCHAR(1000) NULL,
  last_frame_image VARCHAR(1000) NULL,
  video_url VARCHAR(1000) NULL,
  tts_audio_url VARCHAR(1000) NULL,
  subtitle_url VARCHAR(1000) NULL,
  composed_video_url VARCHAR(1000) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  duration INT NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS characters (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drama_id BIGINT NOT NULL,
  name VARCHAR(180) NOT NULL,
  voice_style VARCHAR(180) NULL,
  image_url VARCHAR(1000) NULL,
  voice_sample_url VARCHAR(1000) NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scenes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drama_id BIGINT NOT NULL,
  episode_id BIGINT NULL,
  location VARCHAR(180) NOT NULL,
  time VARCHAR(120) NOT NULL,
  prompt TEXT NOT NULL,
  image_url VARCHAR(1000) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS episodes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drama_id BIGINT NOT NULL,
  episode_number INT NOT NULL,
  title VARCHAR(180) NOT NULL,
  image_config_id BIGINT NULL,
  video_config_id BIGINT NULL,
  audio_config_id BIGINT NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canvas_projects (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(1000) NULL,
  canvas_data LONGTEXT NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_by VARCHAR(64) NULL,
  deleted_at DATETIME NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  KEY idx_canvas_projects_user_updated (user_id, is_deleted, updated_at),
  KEY idx_canvas_projects_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO system_settings (setting_key, setting_value, group_name, label, value_type, created_by, updated_by)
VALUES
  ('site_name', 'Lovarts短剧平台', 'site', '网站名称', 'string', 'system', 'system'),
  ('site_title', 'Lovarts短剧平台', 'site', '网站标题', 'string', 'system', 'system'),
  ('site_description', 'AI短剧创作平台', 'site', '网站描述', 'string', 'system', 'system'),
  ('site_keywords', 'AI短剧,短剧创作,Lovarts', 'site', '网站关键词', 'string', 'system', 'system'),
  ('site_logo_url', '/static/uploads/lovarts-logo.png', 'brand', '网站 Logo', 'image', 'system', 'system'),
  ('default_avatar_url', '', 'brand', '用户默认头像', 'image', 'system', 'system'),
  ('storage_driver', 'local', 'storage', '存储驱动', 'string', 'system', 'system'),
  ('oss_region', '', 'storage', '阿里云 OSS Region', 'string', 'system', 'system'),
  ('oss_bucket', '', 'storage', '阿里云 OSS Bucket', 'string', 'system', 'system'),
  ('oss_endpoint', '', 'storage', '阿里云 OSS Endpoint', 'string', 'system', 'system'),
  ('oss_access_key_id', '', 'storage', '阿里云 OSS AccessKey ID', 'string', 'system', 'system'),
  ('oss_access_key_secret', '', 'storage', '阿里云 OSS AccessKey Secret', 'secret', 'system', 'system'),
  ('oss_public_base_url', '', 'storage', '阿里云 OSS 公网域名', 'string', 'system', 'system'),
  ('daily_login_bonus_credits', '0', 'rewards', '每天登录赠送积分', 'number', 'system', 'system'),
  ('register_bonus_credits', '0', 'rewards', '用户注册赠送积分', 'number', 'system', 'system'),
  ('invite_bonus_credits', '0', 'rewards', '每邀请一人赠送积分', 'number', 'system', 'system')
ON DUPLICATE KEY UPDATE label = VALUES(label), value_type = VALUES(value_type), updated_by = 'system';

INSERT INTO ai_model_parameter_profiles (profile_key, name, service_type, description, is_builtin, created_by, updated_by)
VALUES
  ('image_basic', '图片基础参数', 'image', '图片模型通用参数', 1, 'system', 'system'),
  ('video_basic', '视频基础参数', 'video', '视频模型通用参数', 1, 'system', 'system'),
  ('text_basic', '文本基础参数', 'text', '文本模型通用参数', 1, 'system', 'system'),
  ('audio_basic', '音频基础参数', 'audio', '音频模型通用参数', 1, 'system', 'system')
ON DUPLICATE KEY UPDATE name = VALUES(name), updated_by = 'system';
